version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    networks:
      - OurNetworks-App
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P YourPassword123 -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultSQLConnection=Server=sqlserver,1433;Database=HahnTicket;User Id=sa;Password=YourPassword123;MultipleActiveResultSets=True;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - OurNetworks-App

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - OurNetworks-App

networks:
  OurNetworks-App:
    driver: bridge
